name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the testing docker image
      run: docker build -t partmc-doc -f Dockerfile.doc .
    - name: Run container to generate docs
      run: docker run --name partmc-doc-container partmc-doc
    - name: Copy docs from container to local workspace
      run: docker cp partmc-doc-container:/partmc/doc/html ./docs/html
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
         branch: gh-pages
         folder: docs/html
    - name: Clean up container
      run: docker rm partmc-doc-container
