name: Deploy Doxygen Docs

on:
  push:
    branches: [doxygen]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate and Deploy Doxygen Docs
        uses: AgarwalSaurav/ghaction-doxygen-ghpages@release/v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./doc 
          doxyfile-path: Doxyfile
          html-output-folder: html
          branch: gh-pages

#        uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          config_file: doc/Doxyfile
#          folder: docs/html
#          branch: gh-pages
