name: Deploy Doxygen Docs

on:
  push:
    branches: [doxygen]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate and Deploy Doxygen Docs
        uses: AgarwalSaurav/ghaction-doxygen-ghpages@release/v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          doxyfile-path: Doxyfile
          html-output-folder: docs/html
          branch: gh-pages
