name: Deploy Doxygen Docs

on:
  push:
    branches: [doxygen]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Move to doc folder
        run: cd doc

      - name: Generate and Deploy Doxygen Docs
        uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: Doxyfile
          folder: html
          branch: gh-pages
